import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { describe, expect, it } from "vitest";
import {
  OPERATOR_LOCALES,
  operatorMessage,
  resolveOperatorLocale,
} from "../src/relay/operatorLocale.generated.js";

describe("operator locale contract", () => {
  it("normalizes system locales and has English fallback", () => {
    expect(resolveOperatorLocale("system", "zh-TW")).toBe("zh-CN");
    expect(resolveOperatorLocale("system", "zh")).toBe("zh-CN");
    expect(resolveOperatorLocale("system", "fr-FR")).toBe("en");
    expect(resolveOperatorLocale("unsupported", "en-US")).toBe("en");
    expect(operatorMessage("en", "status.queued")).toBe("Queued");
  });

  it("keeps catalog keys and named placeholders in parity", () => {
    const keys = Object.keys(OPERATOR_LOCALES.en).sort();
    expect(Object.keys(OPERATOR_LOCALES["zh-CN"]).sort()).toEqual(keys);
    for (const key of keys) {
      const names = (value: string) =>
        [...value.matchAll(/\{([A-Za-z][A-Za-z0-9_]*)\}/g)].map((match) => match[1]).sort();
      expect(names(OPERATOR_LOCALES.en[key as keyof typeof OPERATOR_LOCALES.en])).toEqual(
        names(OPERATOR_LOCALES["zh-CN"][key as keyof typeof OPERATOR_LOCALES.en]),
      );
    }
  });

  it("maps every protocol status and preserves unknown raw values", () => {
    const statuses = [
      "uploading",
      "queued",
      "claimed",
      "awaiting-response",
      "completed",
      "cancelled",
      "expired",
    ];
    for (const status of statuses) {
      expect(
        operatorMessage("en", `status.${status}` as keyof typeof OPERATOR_LOCALES.en),
      ).not.toBe(status);
      expect(
        operatorMessage("zh-CN", `status.${status}` as keyof typeof OPERATOR_LOCALES.en),
      ).not.toBe(status);
    }
    const label = (raw: string) =>
      Object.hasOwn(OPERATOR_LOCALES.en, `status.${raw}`)
        ? operatorMessage("en", `status.${raw}` as keyof typeof OPERATOR_LOCALES.en)
        : raw;
    expect(label("future-status")).toBe("future-status");
  });

  it("does not change user-owned content at the display boundary", () => {
    const task = {
      title: "题目 title",
      prompt: "原始 prompt",
      filename: "文件.bin",
      answer: "原始 answer",
    };
    expect(operatorMessage("zh-CN", "task.model", { model: "gpt-example" })).toContain(
      "gpt-example",
    );
    expect(task).toEqual({
      title: "题目 title",
      prompt: "原始 prompt",
      filename: "文件.bin",
      answer: "原始 answer",
    });
  });

  it("interpolates once so user content cannot trigger a second placeholder replacement", () => {
    expect(operatorMessage("en", "new.task.detail", { title: "literal {count}", count: 2 })).toBe(
      "literal {count} · 2 attachments",
    );
  });

  it("checks generated adapter drift through the real check command", async () => {
    const generated = await readFile(
      resolve(import.meta.dirname, "../src/relay/operatorLocale.generated.ts"),
      "utf8",
    );
    expect(generated).toContain("Generated by scripts/generate-operator-locales.mjs");
    const result = spawnSync("node", ["scripts/generate-operator-locales.mjs", "--check"], {
      cwd: resolve(import.meta.dirname, ".."),
      encoding: "utf8",
    });
    expect(result.status, result.stderr).toBe(0);
  });

  it("keeps native localization state instance-safe and live", async () => {
    const root = resolve(import.meta.dirname, "..");
    const [
      windows,
      android,
      androidMain,
      macos,
      web,
      androidGenerated,
      windowsGenerated,
      macosGenerated,
    ] = await Promise.all([
      readFile(resolve(root, "apps/relay-operator-windows/RelayApi.cs"), "utf8"),
      readFile(
        resolve(
          root,
          "apps/relay-operator-android/app/src/main/java/fun/dragonfsky/oraclerelay/RelayPollingService.kt",
        ),
        "utf8",
      ),
      readFile(
        resolve(
          root,
          "apps/relay-operator-android/app/src/main/java/fun/dragonfsky/oraclerelay/MainActivity.kt",
        ),
        "utf8",
      ),
      readFile(
        resolve(
          root,
          "apps/relay-operator-macos/Sources/OracleRelayOperator/OracleRelayOperator.swift",
        ),
        "utf8",
      ),
      readFile(resolve(root, "src/relay/server.ts"), "utf8"),
      readFile(
        resolve(
          root,
          "apps/relay-operator-android/app/src/main/java/fun/dragonfsky/oraclerelay/OperatorLocale.generated.kt",
        ),
        "utf8",
      ),
      readFile(resolve(root, "apps/relay-operator-windows/OperatorLocale.g.cs"), "utf8"),
      readFile(
        resolve(
          root,
          "apps/relay-operator-macos/Sources/OracleRelayOperator/OperatorLocale.generated.swift",
        ),
        "utf8",
      ),
    ]);
    expect(windows).toContain("private async Task EnsureSuccessAsync");
    expect(android).toContain("RelayApi(operatorName) { currentLanguage() }");
    expect(android).toContain("OperatorLocale.t(key, currentLanguage(), values.toMap())");
    expect(macos).toContain("OperatorLanguageSettings.current");
    expect(web).toContain("t('response.files.input')");
    expect(web).not.toContain("+'：'+item.filename");
    expect(web).toContain('replaceAll("<", "\\\\u003c")');
    expect(web).toContain("if(active)updateDetailLanguage()");
    expect(web).not.toContain("if(active)render()");
    expect(web).toContain("function updateDetailLanguage()");
    expect(web).toContain("esc(t('answer.submit'))");
    expect(androidGenerated).toContain("placeholders.replace(template)");
    expect(windowsGenerated).toContain("Placeholders.Replace(template, match =>");
    expect(macosGenerated).toContain("let matches = placeholders.matches(in: template");
    expect(macosGenerated).toContain('static let catalogs = #"""\n{');
    expect(macosGenerated).toContain('\n"""#\n    static let placeholders');
    expect(macos).toContain("updateResponseFileLabel()");
    expect(macos).not.toContain("updateResponseFilesLabel()");
    expect(macos).toContain('basename: "pasted-image-\\(timestamp)-\\(index + 1)"');
    expect(macos).toContain('let base = "attachment-\\(index + 1)"');
    expect(macos).not.toContain('basename: t("attachment.pasted-image"');
    expect(macos).not.toContain('let base = t("attachment.cache"');
    expect(androidMain).toContain('outState.putString("responseDraft"');
    expect(androidMain).toContain('outState.putStringArrayList("responseUris"');
    expect(androidMain).toContain('outState.putString("responseDraftTaskId", activeTask?.id)');
    expect(androidMain).toContain("restoreDraft(savedInstanceState)");
    expect(androidMain).toContain('preferences().getString("activeTaskId", null)');
    expect(androidMain).toContain("applyPendingDraft(task.id)");
  });
});
